---
- block:
  - name: register host
    include_role:
      name: rhsm-subscription

  - name: enable repos
    include_role:
      name: rhsm-repos

  - name: install centos-release-openshift-origin repo
    package:
      name: centos-release-openshift-origin
      state: present
    when: openshift_deployment_type == 'origin'

  - name: check subscription. if this task fails, please check your username, password and pool id
    command: yum list atomic-openshift-utils
    changed_when: false

  - block:
    - name: add google repo
      yum_repository:
        name: google-cloud-compute
        description: Google Cloud Compute
        baseurl: https://packages.cloud.google.com/yum/repos/google-cloud-compute-el7-x86_64
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg\n https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

    - name: remove irqbalance package
      package:
        name: irqbalance
        state: absent
    when: openshift_deployment_type == 'openshift-enterprise'

  - name: install PyYAML for update-instances
    package:
      name: PyYAML
      state: present

  - name: uninstall unnecessary package
    package:
      name: rhevm-guest-agent-common
      state: absent

  - name: update instance
    include_role:
      name: update-instances

  - name: install required packages
    package:
      name:
      - google-compute-engine
      - cloud-init
      - docker
      - iptables-services
      - rng-tools
      - atomic-openshift-clients
      - httpd-tools
      state: present

  - name: enable docker service at boot
    service:
      name: docker
      enabled: yes

  - name: creates /root/bin directory
    file: path=/root/bin state=directory

  - name: creates /var/lib/origin/openshift.local.data directory
    file: path=/var/lib/origin/openshift.local.data state=directory recurse=yes

  - name: create and set exec mode to clusterup script
    file: path=/root/bin/clusterup state=touch mode=0700

  - name: append the clusterup command
    lineinfile:
      path: /root/bin/clusterup
      line: 'oc cluster up --host-data-dir=/var/lib/origin/openshift.local.data --use-existing-config --public-hostname=$OCPHOST --routing-suffix=apps.$OCPHOST'

  - name: add the local insecure registry for openshift
    replace:
      path: /etc/containers/registries.conf
      regexp: '\[registries.insecure\]\nregistries = \[\]'
      replace: '[registries.insecure]\nregistries = ["172.30.0.0/16"]'

  - name: add disk_setup to cloud_config_modules
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      insertafter: '^cloud_config_modules:$'
      line: ' - disk_setup'
      state: present

  - name: clear yum cache
    command: yum clean all

  - name: unregister the system
    include_role:
      name: rhsm-unregister

  - name: enable rngd service
    service:
      name: rngd
      enabled: true

  rescue:
  - name: unregister the system
    include_role:
      name: rhsm-unregister

  - name: delete temp instance
    include_role:
      name: deployment-delete
    vars:
      deployment_name: tmp-instance
    delegate_to: localhost

  - name: delete temp instance disk
    gce_pd:
      name: '{{ prefix }}-tmp-instance'
      zone: '{{ gcloud_zone }}'
      service_account_email: '{{ service_account_id }}'
      credentials_file: '{{ credentials_file }}'
      project_id: '{{ gcloud_project }}'
      state: absent
    delegate_to: localhost

  - name: delete local ssh config for temp instance
    include_role:
      name: ssh-config-tmp-instance-delete
    delegate_to: localhost

  - name: fail after cleanup
    fail:
      msg: Failed to create gold image. Please look for an error in the output above.
